### ISSUE TITLE
Divergence not working as expected

### ISSUE THREAD

**Issue by lit-af** [nagimov/grafcet2#1]
Is it possible to have more than 2 branch under the divergence function?

Thanks

**Comment by nagimov** [comment]
Not really... It's defined as `\newcommand{\Divergence}[2]` so it only accepts 2 args.
I can't see the reason to complicate it with an arbitrary number of arguments when you can just diverge multiple times:
```
       |
  +----+----+
  |         |
  |    +----+----+
  |    |         |
  |    +----+----+
  |         |
  +----+----+
       |
```

**Comment by lit-af** [comment]
Well, it's for a school project, and unless i'm not doing it correctly, the output seems a little messy.

I asked since sometimes, adding a parameter isn't quite complicated, thanks for the quick reply!

![capture d ecran 2016-11-22 a 23 33 02](https://cloud.githubusercontent.com/assets/17530304/20551249/1a5748b4-b10c-11e6-9844-6e4b500a71da.jpg)


`\begin{grafcet}
\Loop{
    \FirstStep{Attente}
    \Divergence{
        \Divergence
        {
            \Transition{$\overline{Erreur}*Init*SelAuto$}
            \Step{Mode auto}
            \Transition{$\overline{Erreur}*Init*SelAuto$}
        }
        {
            \Transition{$\overline{Erreur}*\overline{Init}*SelAuto$}
            \Step{Mode Init}
            \Transition{$INIT+ERREUR$}
        }
        \Nop
    }
    {   \Divergence    
        {
            \Transition{$\overline{SelAuto}$}
            \Step{M. manuel}
            \Transition{zz}
        }
        {
            \Transition{$Erreur*SelAuto$}
            \Step{Erreur globale}
            \Transition{$\overline{Erreur}$}
        }
        \Nop
    }
    
    \Step{SET 24.10}
    \Transition{24.10}
}
\end{grafcet}`
